name: SimpleArenaScript
main: me.kapehh.SimpleArenaScript.SimpleArenaScript
author: kapehh
version: 1.0.0
commands:
    arenascript:
      usage: /<command> <arena> <player>
      description: Simple Arena Script