name: SimpleArenaScript
main: me.kapehh.SimpleArenaScript.SimpleArenaScript
author: kapehh
version: 1.0.0
#commands:
#    enchanterx:
#      usage: /<command> <enchant name> <enchant level>
#      description: